export const USER_LOGOUT = 'USER_LOGOUT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

export const UPDATE_DETAILS_REQUEST = 'UPDATE_DETAILS_REQUEST';
export const UPDATE_DETAILS_SUCCESS = 'UPDATE_DETAILS_SUCCESS';
export const UPDATE_DETAILS_FAILURE = 'UPDATE_DETAILS_FAILURE';

export const GET_ALL_USER_DETAILS_REQUEST = 'GET_ALL_USER__DETAILS_REQUEST';
export const GET_ALL_USER_DETAILS_SUCCESS = 'GET_ALL_USER__DETAILS_SUCCESS';
export const GET_ALL_USER_DETAILS_FAILURE = 'GET_ALL_USER__DETAILS_FAILURE';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';

export const UPDATE_PROFILE_IMAGE_REQUEST = 'UPDATE_PROFILE_IMAGE_REQUEST';
export const UPDATE_PROFILE_IMAGE_SUCESS = 'UPDATE_PROFILE_IMAGE_SUCESS';
export const UPDATE_PROFILE_IMAGE_FAILURE = 'UPDATE_PROFILE_IMAGE_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCESS = 'GET_PROFILE_SUCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCESS = 'UPDATE_PROFILE_SUCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_USERNAME_REQUEST = 'UPDATE_USERNAME_REQUEST';
export const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS';
export const UPDATE_USERNAME_FAIL = 'UPDATE_USERNAME_FAIL';

export const UPDATE_SOCIAL_ACCOUNT_REQUEST = 'UPDATE_SOCIAL_ACCOUNT_REQUEST';
export const UPDATE_SOCIAL_ACCOUNT_SUCCESS = 'UPDATE_SOCIAL_ACCOUNT_SUCCESS';
export const UPDATE_SOCIAL_ACCOUNT_FAIL = 'UPDATE_SOCIAL_ACCOUNT_FAIL';

export const GITHUB_O_AUTH = 'GITHUB_O_AUTH';
export const GITHUB_CALLBACK = 'GITHUB_CALLBACK';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';

export const SAVE_GITHUB_USERNAME_REQUEST = 'SAVE_GITHUB_USERNAME_REQUEST';
export const SAVE_GITHUB_USERNAME_SUCCESS = 'SAVE_GITHUB_USERNAME_SUCESS';
export const SAVE_GITHUB_USERNAME_FAIL = 'SAVE_GITHUB_USERNAME_FAIL';

export const ALL_USER_PROJECTS_REQUEST = 'ALL_USER_PROJECTS_REQUEST';
export const ALL_USER_PROJECTS_SUCCESS = 'ALL_USER_PROJECTS_SUCCESS';
export const ALL_USER_PROJECTS_FAIL = 'ALL_USER_PROJECTS_FAIL';

export const ALL_USER_PROJECTS_BY_ID_REQUEST = 'ALL_USER_PROJECTS_BY_ID_REQUEST';
export const ALL_USER_PROJECTS_BY_ID_SUCCESS = 'ALL_USER_PROJECTS_BY_ID_SUCCESS';
export const ALL_USER_PROJECTS_BY_ID_FAIL = 'ALL_USER_PROJECTS_BY_ID_FAIL';

export const UPDATE_PROJECT_DETAILS_REQUEST = 'UPDATE_PROJECT_DETAILS_REQUEST';
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS';
export const UPDATE_PROJECT_DETAILS_FAIL = 'UPDATE_PROJECT_DETAILS_FAIL';

export const GET_ALL_EDUCATION_LIST_REQUEST = 'GET_ALL_EDUCATION_LIST_REQUEST';
export const GET_ALL_EDUCATION_LIST_SUCCESS = 'GET_ALL_EDUCATION_LIST_SUCCESS';
export const GET_ALL_EDUCATION_LIST_FAIL = 'GET_ALL_EDUCATION_LIST_FAIL';

export const ADD_NEW_EDUCATION_REQUEST = 'ADD_NEW_EDUCATION_REQUEST';
export const ADD_NEW_EDUCATION_SUCCESS = 'ADD_NEW_EDUCATION_SUCCESS';
export const ADD_NEW_EDUCATION_FAIL = 'ADD_NEW_EDUCATION_FAIL';

export const UPDATE_EDUCATION_DETAILS_REQUEST = 'UPDATE_EDUCATION_DETAILS_REQUEST';
export const UPDATE_EDUCATION_DETAILS_SUCCESS = 'UPDATE_EDUCATION_DETAILS_SUCCESS';
export const UPDATE_EDUCATION_DETAILS_FAIL = 'UPDATE_EDUCATION_DETAILS_FAIL';

export const DELETE_EDUCATION_REQUEST = 'DELETE_EDUCATION_REQUEST';
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL';

export const GET_ALL_EXPERIENCE_LIST_REQUEST = 'GET_ALL_EXPERIENCE_LIST_REQUEST';
export const GET_ALL_EXPERIENCE_LIST_SUCCESS = 'GET_ALL_EXPERIENCE_LIST_SUCCESS';
export const GET_ALL_EXPERIENCE_LIST_FAIL = 'GET_ALL_EXPERIENCE_LIST_FAIL';

export const GET_EXPERIENCE_BY_ID_REQUEST = 'GET_EXPERIENCE_BY_ID_REQUEST';
export const GET_EXPERIENCE_BY_ID_SUCCESS = 'GET_EXPERIENCE_BY_ID_SUCCESS';
export const GET_EXPERIENCE_BY_ID_FAIL = 'GET_EXPERIENCE_BY_ID_FAIL';

export const ADD_NEW_EXPERIENCE_REQUEST = 'ADD_NEW_EXPERIENCE_REQUEST';
export const ADD_NEW_EXPERIENCE_SUCCESS = 'ADD_NEW_EXPERIENCE_SUCCESS';
export const ADD_NEW_EXPERIENCE_FAIL = 'ADD_NEW_EXPERIENCE_FAIL';

export const UPDATE_EXPERIENCE_DETAILS_REQUEST = 'UPDATE_EXPERIENCE_DETAILS_REQUEST';
export const UPDATE_EXPERIENCE_DETAILS_SUCCESS = 'UPDATE_EXPERIENCE_DETAILS_SUCCESS';
export const UPDATE_EXPERIENCE_DETAILS_FAIL = 'UPDATE_EXPERIENCE_DETAILS_FAIL';

export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';

export const GET_ALL_CERTIFICATE_LIST_REQUEST = 'GET_ALL_CERTIFICATE_LIST_REQUEST';
export const GET_ALL_CERTIFICATE_LIST_SUCCESS = 'GET_ALL_CERTIFICATE_LIST_SUCCESS';
export const GET_ALL_CERTIFICATE_LIST_FAIL = 'GET_ALL_CERTIFICATE_LIST_FAIL';

export const GET_CERTIFICATE_BY_ID_REQUEST = 'GET_CERTIFICATE_BY_ID_REQUEST';
export const GET_CERTIFICATE_BY_ID_SUCCESS = 'GET_CERTIFICATE_BY_ID_SUCCESS';
export const GET_CERTIFICATE_BY_ID_FAIL = 'GET_CERTIFICATE_BY_ID_FAIL';

export const ADD_NEW_CERTIFICATE_REQUEST = 'ADD_NEW_CERTIFICATE_REQUEST';
export const ADD_NEW_CERTIFICATE_SUCCESS = 'ADD_NEW_CERTIFICATE_SUCCESS';
export const ADD_NEW_CERTIFICATE_FAIL = 'ADD_NEW_CERTIFICATE_FAIL';

export const UPDATE_CERTIFICATE_DETAILS_REQUEST = 'UPDATE_CERTIFICATE_DETAILS_REQUEST';
export const UPDATE_CERTIFICATE_DETAILS_SUCCESS = 'UPDATE_CERTIFICATE_DETAILS_SUCCESS';
export const UPDATE_CERTIFICATE_DETAILS_FAIL = 'UPDATE_CERTIFICATE_DETAILS_FAIL';

export const DELETE_CERTIFICATE_REQUEST = 'DELETE_CERTIFICATE_REQUEST';
export const DELETE_CERTIFICATE_SUCCESS = 'DELETE_CERTIFICATE_SUCCESS';
export const DELETE_CERTIFICATE_FAIL = 'DELETE_CERTIFICATE_FAIL';

export const RESET_EDUCATION_DETAILS = 'RESET_EDUCATION_DETAILS';
export const RESET_EXPERIENCE_DETAILS = 'RESET_EXPERIENCE_DETAILS';

export const SET_CODECHEF_USERNAME_REQUEST = 'SET_CODECHEF_USERNAME_REQUEST';
export const SET_CODECHEF_USERNAME_SUCCESS = 'SET_CODECHEF_USERNAME_SUCCESS';
export const SET_CODECHEF_USERNAME_FAIL = 'SET_CODECHEF_USERNAME_FAIL';

export const GET_CODECHEF_DATA_REQUEST = 'GET_CODECHEF_DATA_REQUEST';
export const GET_CODECHEF_DATA_SUCCESS = 'GET_CODECHEF_DATA_SUCCESS';
export const GET_CODECHEF_DATA_FAIL = 'GET_CODECHEF_DATA_FAIL';

export const SET_SPOJ_USERNAME_REQUEST = 'SET_SPOJ_USERNAME_REQUEST';
export const SET_SPOJ_USERNAME_SUCCESS = 'SET_SPOJ_USERNAME_SUCCESS';
export const SET_SPOJ_USERNAME_FAIL = 'SET_SPOJ_USERNAME_FAIL';

export const GET_SPOJ_DATA_REQUEST = 'GET_SPOJ_DATA_REQUEST';
export const GET_SPOJ_DATA_SUCCESS = 'GET_SPOJ_DATA_SUCCESS';
export const GET_SPOJ_DATA_FAIL = 'GET_SPOJ_DATA_FAIL';

export const SET_CODEFORCES_USERNAME_REQUEST = 'SET_CODEFORCES_USERNAME_REQUEST';
export const SET_CODEFORCES_USERNAME_SUCCESS = 'SET_CODEFORCES_USERNAME_SUCCESS';
export const SET_CODEFORCES_USERNAME_FAIL = 'SET_CODEFORCES_USERNAME_FAIL';

export const GET_CODEFORCES_DATA_REQUEST = 'GET_CODEFORCES_DATA_REQUEST';
export const GET_CODEFORCES_DATA_SUCCESS = 'GET_CODEFORCES_DATA_SUCCESS';
export const GET_CODEFORCES_DATA_FAIL = 'GET_CODEFORCES_DATA_FAIL';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const GET_ALL_EDUCATION_REQUEST = 'GET_ALL_EDUCATION_REQUEST';
export const GET_ALL_EDUCATION_SUCCESS = 'GET_ALL_EDUCATION_SUCCESS';
export const GET_ALL_EDUCATION_FAILURE = 'GET_ALL_EDUCATION_FAILURE';

export const GET_EDUCATION_BY_ID_REQUEST = 'GET_EDUCATION_REQUEST';
export const GET_EDUCATION_BY_ID_SUCCESS = 'GET_EDUCATION_SUCCESS';
export const GET_EDUCATION_BY_ID_FAILURE = 'GET_EDUCATION_FAILURE';

export const UPDATE_EDUCATION_REQUEST = 'UPDATE_EDUCATION_REQUEST';
export const UPDATE_EDUCATION_SUCCESS = 'UPDATE_EDUCATION_SUCCESS';
export const UPDATE_EDUCATION_FAILURE = 'UPDATE_EDUCATION_FAILURE';

export const GET_EXPERIENCE_REQUEST = 'GET_EXPERIENCE_REQUEST';
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS';
export const GET_EXPERIENCE_FAILURE = 'GET_EXPERIENCE_FAILURE';

export const GET_ALL_EXPERIENCE_REQUEST = 'GET_ALL_EXPERIENCE_REQUEST';
export const GET_ALL_EXPERIENCE_SUCCESS = 'GET_ALL_EXPERIENCE_SUCCESS';
export const GET_ALL_EXPERIENCE_FAILURE = 'GET_ALL_EXPERIENCE_FAILURE';

export const UPDATE_EXPERIENCE_REQUEST = 'UPDATE_EXPERIENCE_REQUEST';
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS';
export const UPDATE_EXPERIENCE_FAILURE = 'UPDATE_EXPERIENCE_FAILURE';

export const LOADING_ENABLE = 'LOADING_ENABLE';
export const LOADING_DISABLE = 'LOADING_DISABLE';

export const ERROR = 'ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const DEFAULT_STATE = 'DEFAULT_STATE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const GET_USER = 'GET_USER';








