export const USER_LOGOUT = 'USER_LOGOUT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

export const UPDATE_DETAILS_REQUEST = 'UPDATE_DETAILS_REQUEST';
export const UPDATE_DETAILS_SUCCESS = 'UPDATE_DETAILS_SUCCESS';
export const UPDATE_DETAILS_FAILURE = 'UPDATE_DETAILS_FAILURE';

export const GET_ALL_USER_DETAILS_REQUEST = 'GET_ALL_USER__DETAILS_REQUEST';
export const GET_ALL_USER_DETAILS_SUCCESS = 'GET_ALL_USER__DETAILS_SUCCESS';
export const GET_ALL_USER_DETAILS_FAILURE = 'GET_ALL_USER__DETAILS_FAILURE';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';


export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCESS = 'GET_PROFILE_SUCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCESS = 'UPDATE_PROFILE_SUCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';


export const UPDATE_SOCIAL_ACCOUNT_REQUEST = 'UPDATE_SOCIAL_ACCOUNT_REQUEST';
export const UPDATE_SOCIAL_ACCOUNT_SUCCESS = 'UPDATE_SOCIAL_ACCOUNT_SUCCESS';
export const UPDATE_SOCIAL_ACCOUNT_FAIL = 'UPDATE_SOCIAL_ACCOUNT_FAIL';



export const LOADING_ENABLE = 'LOADING_ENABLE';
export const LOADING_DISABLE = 'LOADING_DISABLE';

export const ERROR = 'ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const DEFAULT_STATE = 'DEFAULT_STATE';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const GET_USER = 'GET_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';

export const GET_ANALTICS = 'GET_ANALTICS';

export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const GET_EDUCATION = 'GET_EDUCATION';

export const GET_EDUCATION_BY_ID = 'GET_EDUCATION_BY_ID';
export const DELETE_EDUCATION_BY_ID = 'DELETE_EDUCATION_BY_ID';
export const UPDATE_EDUCATION_BY_ID = 'UPDATE_EDUCATION_BY_ID';

export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
export const GET_EXPERIENCE = 'GET_EXPERIENCE';

export const GET_EXPERIENCE_BY_ID = 'GET_EXPERIENCE_BY_ID';
export const DELETE_EXPERIENCE_BY_ID = 'DELETE_EXPERIENCE_BY_ID';
export const UPDATE_EXPERIENCE_BY_ID = 'UPDATE_EXPERIENCE_BY_ID';

export const GITHUB_CALLBACK = 'GITHUB_CALLBACK';


export const CREATE_PROJECT = 'CREATE_PROJECT';
export const GET_PROJECT = 'GET_PROJECT';
export const REFRESH_PROJECT = 'REFRESH_PROJECT';

export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const DELETE_PROJECT_BY_ID = 'DELETE_PROJECT_BY_ID';
export const UPDATE_PROJECT_BY_ID = 'UPDATE_PROJECT_BY_ID';

export const CHECK_DOMAIN = 'CHECK_DOMAIN';

export const GET_SKILLS = 'GET_SKILLS';
export const ADD_SKILLS = 'ADD_SKILLS';
export const DELETE_SKILLS = 'DELETE_SKILLS';


















